# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: clan.proto
# Protobuf Python Version: 6.33.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    1,
    '',
    'clan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nclan.proto\x12\x08\x66reefire\"\'\n\nMemberInfo\x12\x0b\n\x03uid\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x03 \x01(\t\"n\n\x0f\x43lanMemberEntry\x12\"\n\x04info\x18\x01 \x01(\x0b\x32\x14.freefire.MemberInfo\x12\x0c\n\x04role\x18\x04 \x01(\r\x12\x13\n\x0btotal_glory\x18\x0b \x01(\r\x12\x14\n\x0cweekly_glory\x18\r \x01(\r\"D\n\x16GetClanMembersResponse\x12*\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x19.freefire.ClanMemberEntryb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MEMBERINFO']._serialized_start=24
  _globals['_MEMBERINFO']._serialized_end=63
  _globals['_CLANMEMBERENTRY']._serialized_start=65
  _globals['_CLANMEMBERENTRY']._serialized_end=175
  _globals['_GETCLANMEMBERSRESPONSE']._serialized_start=177
  _globals['_GETCLANMEMBERSRESPONSE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
